// packages/angular/src/TrackerComponent.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  Directive,
  ElementRef,
  NgZone,
  OnDestroy,
  PLATFORM_ID,
  Renderer2,
  ViewChild,
  computed,
  effect,
  inject,
  input,
  output,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { resolveTrackerOptions } from '@rightxt/tracker-core';
import { projectTrackerChromeView } from '@rightxt/tracker-core/projection';
import {
  TrackerProjectionElementDirective,
  applyElementView,
  attemptAdapterCleanup,
  createProjectionRuntime,
  createRuntimeConfiguration,
  throwAdapterLifecycleErrors,
} from './projectionAdapter.js';

import type {
  TrackerClusterActivateEventPayload,
  TrackerEventUnsubscribe,
  TrackerMarkerActivateEventPayload,
  TrackerOptions,
  TrackerRule,
  TrackerScrollRoot,
  TrackerSelectionChangeEventPayload,
  TrackerSourceRoot,
  TrackerState,
  TrackerStats,
  TrackerSyncEndEventPayload,
  TrackerSyncStartEventPayload,
  TrackerTrackActivateEventPayload,
  TrackerWarningEventPayload,
} from '@rightxt/tracker-core';
import type { TrackerItemView } from '@rightxt/tracker-core/projection';
import type { AppliedElementViewNames } from './projectionAdapter.js';

/** Applies selection transitions to registered keyed item elements. */
class AngularItemRegistry {
  readonly #elements = new Map<string, HTMLElement>();
  readonly #renderer: Renderer2;
  #selectedKey: string | null = null;

  /**
   * @param renderer - Angular renderer used for selection attribute ownership.
   */
  constructor(renderer: Renderer2) {
    this.#renderer = renderer;
  }

  /** Registers one live item element and synchronizes its selected state. */
  register(key: string, element: HTMLElement): void {
    this.#elements.set(key, element);

    if (key === this.#selectedKey) {
      this.#renderer.setAttribute(element, 'data-rxtt-selected', 'true');
    } else {
      this.#renderer.removeAttribute(element, 'data-rxtt-selected');
    }
  }

  /** Removes a key only when it still points to the retiring element. */
  unregister(key: string, element: HTMLElement): void {
    if (this.#elements.get(key) === element) {
      this.#elements.delete(key);
    }
  }

  /** Applies one Core selection transition without invalidating the item view. */
  select(previousKey: string | null, selectedKey: string | null): void {
    if (previousKey !== null && previousKey !== selectedKey) {
      const previousElement = this.#elements.get(previousKey);

      if (previousElement !== undefined) {
        this.#renderer.removeAttribute(previousElement, 'data-rxtt-selected');
      }
    }

    if (selectedKey !== null) {
      const selectedElement = this.#elements.get(selectedKey);

      if (selectedElement !== undefined) {
        this.#renderer.setAttribute(selectedElement, 'data-rxtt-selected', 'true');
      }
    }

    this.#selectedKey = selectedKey;
  }
}

/** Applies a pre-projected item view with no per-item signals or effects. */
@Directive({
  selector: '[rxtProjectionItem]',
  standalone: true,
})
class TrackerProjectionItemDirective implements OnDestroy {
  /** Current immutable item view. */
  readonly view = input.required<TrackerItemView>({ alias: 'rxtProjectionItem' });

  /** Registry shared by the item layer. */
  readonly registry = input.required<AngularItemRegistry>();

  readonly #element = inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  readonly #renderer = inject(Renderer2);
  readonly #applied: AppliedElementViewNames = { attributeNames: new Set(), styleVariableNames: new Set() };
  #registeredKey: string | null = null;

  constructor() {
    effect(() => {
      const view = this.view();
      const registry = this.registry();

      if (this.#registeredKey !== null && this.#registeredKey !== view.key) {
        registry.unregister(this.#registeredKey, this.#element);
      }

      applyElementView(this.#renderer, this.#element, view, this.#applied);
      registry.register(view.key, this.#element);
      this.#registeredKey = view.key;
    });
  }

  /** Releases the retiring element from the shared registry. */
  ngOnDestroy(): void {
    if (this.#registeredKey !== null) {
      this.registry().unregister(this.#registeredKey, this.#element);
    }
  }
}

/** Angular visual tree with a single reactive boundary for all items. */
const TRACKER_PROJECTION_TEMPLATE = `
  <div #renderRoot [rxtProjectionElement]="rootView">
    <div [rxtProjectionElement]="viewport" [hidden]="viewport().hidden"></div>
    <div [rxtProjectionElement]="markersLayerView" [hidden]="markersLayerView().hidden">
      @for (item of items(); track item.key) {
        <div [rxtProjectionItem]="item" [registry]="itemRegistry"></div>
      }
    </div>
  </div>
`;

/** Angular Tracker component with domain signals and one non-reactive writer per keyed item. */
@Component({
  selector: 'rxt-tracker-angular',
  standalone: true,
  imports: [TrackerProjectionElementDirective, TrackerProjectionItemDirective],
  template: TRACKER_PROJECTION_TEMPLATE,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
class TrackerComponent implements AfterViewInit, OnDestroy {
  /** Non-rule Tracker options. An explicitly `undefined` value is treated as omission. */
  readonly options = input<Partial<TrackerOptions> | undefined>({});

  /** Authoritative immutable rule list. */
  readonly rules = input<readonly TrackerRule[] | undefined>();

  /** Source query root. Null keeps the adapter unmounted. */
  readonly sourceRoot = input<TrackerSourceRoot | null | undefined>();

  /** Represented page or element viewport. Null keeps the adapter unmounted. */
  readonly scrollRoot = input<TrackerScrollRoot | null | undefined>();

  /** Emits marker activation payloads. */
  readonly markerActivate = output<TrackerMarkerActivateEventPayload>();

  /** Emits cluster activation payloads. */
  readonly clusterActivate = output<TrackerClusterActivateEventPayload>();

  /** Emits after a Core synchronization transaction succeeds. */
  readonly syncEnd = output<TrackerSyncEndEventPayload>();

  /** Emits when a Core synchronization transaction starts. */
  readonly syncStart = output<TrackerSyncStartEventPayload>();

  /** Emits when the committed logical selection changes. */
  readonly selectionChange = output<TrackerSelectionChangeEventPayload>();

  /** Emits when the track is activated to scroll to a position. */
  readonly trackActivate = output<TrackerTrackActivateEventPayload>();

  /** Emits runtime warnings. */
  readonly warning = output<TrackerWarningEventPayload>();

  /** Template-reference query for the root render host. */
  @ViewChild('renderRoot') private renderRootElementRef?: ElementRef<HTMLElement>;

  readonly #ngZone = inject(NgZone);
  readonly #runtime = this.#ngZone.runOutsideAngular(() => createProjectionRuntime({ options: {}, rules: [] }));

  /** Whether this component generation may connect Core to live browser DOM. */
  readonly #isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
  /**
   * Validated configuration shared by chrome rendering and Core mounting.
   * Throws for invalid options or rules on every platform, so a bad input
   * fails identically during server rendering and browser hydration instead
   * of silently defaulting on the server and only surfacing once the client
   * attempts to mount.
   */
  readonly #configuration = computed(() => createRuntimeConfiguration(this.options(), this.rules()));
  readonly #resolvedOptions = computed(() => resolveTrackerOptions(this.#configuration().options));
  readonly #chrome = computed(() => projectTrackerChromeView(this.#resolvedOptions(), this.#runtime.stores.mount()));

  /** Isolated root-element view. */
  readonly rootView = computed(() => this.#chrome().root);

  /** Isolated markers-layer view. */
  readonly markersLayerView = computed(() => this.#chrome().markersLayer);

  /** Isolated viewport-domain signal. */
  readonly viewport = this.#runtime.stores.viewport;

  /** Isolated items-domain signal. */
  readonly items = this.#runtime.stores.items;

  /** Registry providing O(1) selection without per-item reactive consumers. */
  readonly itemRegistry = new AngularItemRegistry(inject(Renderer2));

  #viewReady = false;
  #eventUnsubscribes: TrackerEventUnsubscribe[] = [];
  #appliedSourceRoot: TrackerSourceRoot | null | undefined;
  #appliedScrollRoot: TrackerScrollRoot | null | undefined;
  #appliedOptions: Partial<TrackerOptions> | undefined;
  #appliedRules: readonly TrackerRule[] | undefined;

  constructor() {
    effect(() => {
      const selection = this.#runtime.stores.selection();

      this.itemRegistry.select(selection.previousKey, selection.selectedKey);
    });

    effect(() => {
      const options = this.options();
      const rules = this.rules();
      const sourceRoot = this.sourceRoot();
      const scrollRoot = this.scrollRoot();

      if (!this.#viewReady || !this.#isBrowser) {
        return;
      }

      const configurationChanged = !Object.is(options, this.#appliedOptions) || !Object.is(rules, this.#appliedRules);
      const rootsChanged =
        !Object.is(sourceRoot, this.#appliedSourceRoot) ||
        !Object.is(scrollRoot, this.#appliedScrollRoot) ||
        (sourceRoot !== null && scrollRoot !== null && !this.#runtime.integration.isMounted());

      if (rootsChanged) {
        this.#remount(configurationChanged);
      } else if (configurationChanged) {
        this.#applyOptionsAndRules();
      }
    });
  }

  /** Connects event subscriptions before mounting the Core runtime. */
  ngAfterViewInit(): void {
    this.#viewReady = true;

    if (!this.#isBrowser) {
      return;
    }

    this.#eventUnsubscribes.push(
      this.#runtime.integration.on('marker:activate', (payload) => this.#emit(this.markerActivate, payload)),
      this.#runtime.integration.on('cluster:activate', (payload) => this.#emit(this.clusterActivate, payload)),
      this.#runtime.integration.on('sync:start', (payload) => this.#emit(this.syncStart, payload)),
      this.#runtime.integration.on('sync:end', (payload) => this.#emit(this.syncEnd, payload)),
      this.#runtime.integration.on('selection:change', (payload) => this.#emit(this.selectionChange, payload)),
      this.#runtime.integration.on('track:activate', (payload) => this.#emit(this.trackActivate, payload)),
      this.#runtime.integration.on('warning', (payload) => this.#emit(this.warning, payload)),
    );

    // A failed initial mount leaves Core's own runtime rolled back to a live
    // `unmounted` state (see `mountTrackerInstance()`), not destroyed. Keep
    // `#viewReady` true and the runtime/event bridges intact — rather than
    // tearing them down here — so the reconciliation `effect()` above can
    // recover the same generation once the caller corrects
    // `sourceRoot`/`scrollRoot`. Full destruction stays reserved for genuine
    // teardown in `ngOnDestroy()`.
    this.#remount(true);
  }

  /** Destroys the owned runtime and releases external subscriptions. */
  ngOnDestroy(): void {
    const errors: unknown[] = [];

    this.#releaseRuntimeResources(errors);
    throwAdapterLifecycleErrors(errors, 'Angular Tracker projection destruction failed.');
  }

  /** Returns the current lifecycle state. */
  getState(): TrackerState {
    return this.#runtime.integration.getState();
  }

  /** Returns the current diagnostics snapshot. */
  getStats(): TrackerStats {
    return this.#runtime.integration.getStats();
  }

  /** Performs an immediate refresh. */
  refresh(): void {
    this.#ngZone.runOutsideAngular(() => this.#runtime.integration.render());
  }

  /** Requests a coalesced refresh. */
  requestRefresh(): void {
    this.#ngZone.runOutsideAngular(() => this.#runtime.integration.requestRender());
  }

  /** Resets diagnostic counters. */
  resetStats(): void {
    this.#runtime.integration.resetStats();
  }

  /** Resolves after this Core runtime generation is permanently destroyed. */
  whenRuntimeDestroyed(): Promise<void> {
    return this.#runtime.integration.whenDestroyed();
  }

  /** Applies current immutable options and authoritative rules. */
  #applyOptionsAndRules(): void {
    const configuration = this.#configuration();

    this.#ngZone.runOutsideAngular(() => {
      this.#runtime.integration.replaceConfiguration(configuration);

      if (this.#runtime.integration.isMounted()) {
        this.#runtime.integration.flushRender();
      }
    });
    this.#appliedOptions = this.options();
    this.#appliedRules = this.rules();
  }

  /** Remounts Core against the current DOM-reference identities. */
  #remount(applyConfiguration = false): void {
    const runtimeConfiguration = this.#configuration();

    this.#ngZone.runOutsideAngular(() => {
      if (this.#runtime.integration.isMounted()) {
        this.#runtime.integration.unmount();
      }

      if (applyConfiguration) {
        this.#runtime.integration.replaceConfiguration(runtimeConfiguration);
      }
    });

    // Checkpoint immediately: replaceConfiguration() above already committed, independent of
    // whether the mount attempt below (for a root change bundled into the same update)
    // subsequently succeeds or throws.
    if (applyConfiguration) {
      this.#appliedOptions = this.options();
      this.#appliedRules = this.rules();
    }

    const renderRoot = this.renderRootElementRef;
    const sourceRoot = this.sourceRoot();
    const scrollRoot = this.scrollRoot();

    this.#ngZone.runOutsideAngular(() => {
      if (renderRoot !== undefined && sourceRoot !== null && scrollRoot !== null) {
        this.#runtime.integration.mount({
          ...(sourceRoot === undefined ? {} : { sourceRoot }),
          ...(scrollRoot === undefined ? {} : { scrollRoot }),
          renderRoot: renderRoot.nativeElement,
        });
      }
    });

    // Reached only when mount() above either succeeded or was intentionally skipped (null
    // roots); a thrown mount leaves this reflecting the roots of the last actually-mounted
    // generation instead of the rejected candidate.
    this.#appliedSourceRoot = sourceRoot;
    this.#appliedScrollRoot = scrollRoot;
  }

  /** Destroys the runtime and releases every adapter-owned subscription. */
  #releaseRuntimeResources(errors: unknown[]): void {
    attemptAdapterCleanup(() => this.#ngZone.runOutsideAngular(() => this.#runtime.integration.destroy()), errors);
    this.#eventUnsubscribes.forEach((unsubscribe) => attemptAdapterCleanup(unsubscribe, errors));
    this.#eventUnsubscribes = [];
  }

  /** Emits one runtime payload inside Angular's zone. */
  #emit<TPayload>(emitter: { emit: (payload: TPayload) => void }, payload: TPayload): void {
    this.#ngZone.run(() => emitter.emit(payload));
  }
}

export { AngularItemRegistry, TrackerComponent, TrackerProjectionItemDirective };

// packages/react/src/Tracker.tsx
import { memo, useImperativeHandle, useLayoutEffect, useMemo, useRef, useSyncExternalStore } from 'react';

import { assertValidTrackerConfiguration, resolveTrackerOptions } from '@rightxt/tracker-core';

import {
  DATA_ATTRIBUTES,
  createTrackerProjectionIntegration,
  projectTrackerChromeView,
} from '@rightxt/tracker-core/projection';
import { createReactProjectionStores } from './projectionStores.js';
import { reportHostError } from './reportHostError.js';

import type {
  TrackerClusterActivateEventPayload,
  TrackerEventUnsubscribe,
  TrackerMarkerActivateEventPayload,
  TrackerOptions,
  TrackerReadonlyOptions,
  TrackerRule,
  TrackerScrollRoot,
  TrackerSelectionChangeEventPayload,
  TrackerSourceRoot,
  TrackerState,
  TrackerStats,
  TrackerSyncEndEventPayload,
  TrackerSyncStartEventPayload,
  TrackerTrackActivateEventPayload,
  TrackerWarningEventPayload,
} from '@rightxt/tracker-core';
import type {
  TrackerElementView,
  TrackerItemView,
  TrackerProjectionIntegration,
} from '@rightxt/tracker-core/projection';
import type { CSSProperties, HTMLAttributes, ReactElement, Ref } from 'react';
import type { ReactProjectionStore, ReactProjectionStores } from './projectionStores.js';

/** Framework-native public React handle. */
interface TrackerHandle {
  /** Returns current runtime state. */
  getState: () => TrackerState;
  /** Returns current diagnostics counters. */
  getStats: () => TrackerStats;
  /** Performs an immediate refresh. */
  refresh: () => void;
  /** Resolves after this Core runtime generation is permanently destroyed. */
  whenRuntimeDestroyed: () => Promise<void>;
  /** Resets diagnostics counters. */
  resetStats: () => void;
  /** Requests a coalesced refresh. */
  requestRefresh: () => void;
}

/** Framework-native React component props. */
interface TrackerProps {
  /** Called when a marker cluster is activated. */
  onClusterActivate?: (payload: TrackerClusterActivateEventPayload) => void;
  /** Called when a marker is activated. */
  onMarkerActivate?: (payload: TrackerMarkerActivateEventPayload) => void;
  /** Called when the committed logical selection changes. */
  onSelectionChange?: (payload: TrackerSelectionChangeEventPayload) => void;
  /** Called after a Core synchronization transaction succeeds. */
  onSyncEnd?: (payload: TrackerSyncEndEventPayload) => void;
  /** Called when a Core synchronization transaction starts. */
  onSyncStart?: (payload: TrackerSyncStartEventPayload) => void;
  /** Called when the track is activated to scroll to a position. */
  onTrackActivate?: (payload: TrackerTrackActivateEventPayload) => void;
  /** Called when runtime validation or diagnostics emit a warning. */
  onWarning?: (payload: TrackerWarningEventPayload) => void;
  /** Non-rule Tracker options. */
  options?: Partial<TrackerOptions> | undefined;
  /** React 19 ref-as-prop handle. */
  ref?: Ref<TrackerHandle> | undefined;
  /** Authoritative immutable rule list. */
  rules?: readonly TrackerRule[] | undefined;
  /** Represented page or element viewport. Null keeps Core unmounted. */
  scrollRoot?: TrackerScrollRoot | null | undefined;
  /** Source query root. Null keeps Core unmounted. */
  sourceRoot?: TrackerSourceRoot | null | undefined;
}

/** Runtime and domain stores owned by one React component generation. */
interface ReactProjectionRuntime {
  /** Narrow Core integration. */
  readonly integration: TrackerProjectionIntegration;
  /** Independently observable React domains. */
  readonly stores: ReactProjectionStores;
}

/** Stable omitted-options value. */
const EMPTY_OPTIONS: Partial<TrackerOptions> = {};

/** Delivers one React callback prop without returning consumer failures to Core. */
function notifyConsumer<TPayload>(callback: ((payload: TPayload) => void) | undefined, payload: TPayload): void {
  try {
    callback?.(payload);
  } catch (error) {
    reportHostError(error);
  }
}

/**
 * Runs one adapter-owned cleanup without suppressing subsequent cleanup.
 *
 * @param cleanup - Cleanup operation.
 * @param errors - Mutable error collection.
 */
function attemptAdapterCleanup(cleanup: () => void, errors: unknown[]): void {
  try {
    cleanup();
  } catch (error) {
    errors.push(error);
  }
}

/**
 * Runs deferred teardown without throwing outside React's lifecycle.
 *
 * @param cleanup - Deferred cleanup operation.
 */
function attemptDeferredAdapterCleanup(cleanup: () => void): void {
  try {
    cleanup();
  } catch {
    // Deferred teardown has no active React error boundary.
  }
}

/**
 * Throws one lifecycle error directly or combines multiple failures.
 *
 * @param errors - Ordered lifecycle errors.
 * @param message - Aggregate error message.
 */
function throwAdapterLifecycleErrors(errors: unknown[], message: string): void {
  if (errors.length === 1) {
    throw errors[0];
  }

  if (errors.length > 1) {
    throw new AggregateError(errors, message);
  }
}

/** Converts framework-neutral attributes to React DOM props. */
function createReactAttributes(attributes: Readonly<Record<string, string>>): HTMLAttributes<HTMLDivElement> {
  const { tabindex, ...rest } = attributes;

  return {
    ...rest,
    ...(tabindex === undefined ? {} : { tabIndex: Number(tabindex) }),
  } as HTMLAttributes<HTMLDivElement>;
}

/** Converts framework-neutral CSS variables to React style props. */
function createReactStyle(styleVars: Readonly<Record<string, string>>): CSSProperties {
  return styleVars as CSSProperties;
}

/**
 * Creates and validates an immutable complete configuration.
 *
 * @param options - Tracker options.
 * @param rules - Tracker rules.
 * @returns Validated detached configuration.
 */
function createRuntimeConfiguration(
  options: Partial<TrackerOptions>,
  rules: readonly TrackerRule[] | undefined,
): { options: Partial<TrackerOptions>; rules: readonly TrackerRule[] } {
  if (options !== null && typeof options === 'object' && Object.hasOwn(options, 'rules')) {
    throw new TypeError('React Tracker rules must be passed through the dedicated rules prop.');
  }

  const configuration = { options, rules: rules === undefined ? [] : rules };

  assertValidTrackerConfiguration(configuration);

  return { options: { ...options }, rules: [...configuration.rules] };
}

/**
 * Creates one Tracker runtime and connects its coherent commit coordinator.
 *
 * @param configuration - Initial complete configuration.
 * @param configuration.options - Initial Tracker options.
 * @param configuration.rules - Initial Tracker rules.
 * @returns Runtime and React domain stores.
 */
function createProjectionRuntime(configuration: {
  options: Partial<TrackerOptions>;
  rules: readonly TrackerRule[];
}): ReactProjectionRuntime {
  const integration = createTrackerProjectionIntegration(configuration);
  const stores = createReactProjectionStores(integration.getProjection());

  integration.subscribeProjection(stores.applyCommit);

  return { integration, stores };
}

/** Renders one keyed item and observes only its own selected boolean. */
const TrackerProjectionItem = memo(function TrackerProjectionItemComponent({
  item,
  selection,
}: {
  item: TrackerItemView;
  selection: ReactProjectionStore<boolean>;
}): ReactElement {
  const selected = useSyncExternalStore(selection.subscribe, selection.getSnapshot, selection.getSnapshot);
  const attributes = {
    ...createReactAttributes(item.attributes),
    ...(selected ? { [DATA_ATTRIBUTES.SELECTED]: 'true' } : {}),
  };

  return <div {...attributes} className={item.className} style={createReactStyle(item.styleVars)} />;
});

/** Renders keyed structure only when the items-domain reference changes. */
const TrackerProjectionItems = memo(function TrackerProjectionItemsComponent({
  stores,
}: {
  stores: ReactProjectionStores;
}): ReactElement {
  const items = useSyncExternalStore(stores.items.subscribe, stores.items.getSnapshot, stores.items.getSnapshot);

  return (
    <>
      {items.map((item) => (
        <TrackerProjectionItem key={item.key} item={item} selection={stores.getItemSelection(item.key)} />
      ))}
    </>
  );
});

/** Renders marker-layer chrome independently from item structure. */
const TrackerProjectionMarkers = memo(function TrackerProjectionMarkersComponent({
  layer,
  stores,
}: {
  layer: TrackerElementView & { readonly hidden: boolean };
  stores: ReactProjectionStores;
}): ReactElement {
  return (
    <div
      {...createReactAttributes(layer.attributes)}
      className={layer.className}
      hidden={layer.hidden}
      style={createReactStyle(layer.styleVars)}
    >
      <TrackerProjectionItems stores={stores} />
    </div>
  );
});

/** Renders only the independently observable viewport domain. */
const TrackerProjectionViewport = memo(function TrackerProjectionViewportComponent({
  store,
}: {
  store: ReactProjectionStore<TrackerElementView & { readonly hidden: boolean }>;
}): ReactElement {
  const viewport = useSyncExternalStore(store.subscribe, store.getSnapshot, store.getSnapshot);

  return (
    <div
      {...createReactAttributes(viewport.attributes)}
      className={viewport.className}
      hidden={viewport.hidden}
      style={createReactStyle(viewport.styleVars)}
    />
  );
});

/** Renders root chrome while memoized children retain independent subscriptions. */
const TrackerProjectionTree = memo(function TrackerProjectionTreeComponent({
  options,
  renderRootRef,
  stores,
}: {
  options: TrackerReadonlyOptions;
  renderRootRef: Ref<HTMLDivElement>;
  stores: ReactProjectionStores;
}): ReactElement {
  const mount = useSyncExternalStore(stores.mount.subscribe, stores.mount.getSnapshot, stores.mount.getSnapshot);
  const chrome = projectTrackerChromeView(options, mount);
  const root = chrome.root;

  return (
    <div
      {...createReactAttributes(root.attributes)}
      className={root.className}
      ref={renderRootRef}
      style={createReactStyle(root.styleVars)}
    >
      <TrackerProjectionViewport store={stores.viewport} />
      <TrackerProjectionMarkers layer={chrome.markersLayer} stores={stores} />
    </div>
  );
});

/** Declarative React 19 Tracker backed by projection-domain external stores. */
function Tracker({
  onClusterActivate,
  onMarkerActivate,
  onSelectionChange,
  onSyncEnd,
  onSyncStart,
  onTrackActivate,
  onWarning,
  options = EMPTY_OPTIONS,
  ref,
  rules,
  scrollRoot,
  sourceRoot,
}: TrackerProps): ReactElement {
  const configuration = useMemo(() => createRuntimeConfiguration(options, rules), [options, rules]);
  const resolvedOptions = useMemo(() => resolveTrackerOptions(configuration.options), [configuration]);
  const runtimeRef = useRef<ReactProjectionRuntime | null>(null);
  const renderRootRef = useRef<HTMLDivElement | null>(null);
  const appliedRef = useRef<{
    options: Partial<TrackerOptions>;
    rules: readonly TrackerRule[] | undefined;
    scrollRoot: TrackerScrollRoot | null | undefined;
    sourceRoot: TrackerSourceRoot | null | undefined;
  } | null>(null);
  const lifecycleGenerationRef = useRef(0);
  const callbacksRef = useRef({
    onClusterActivate,
    onMarkerActivate,
    onSelectionChange,
    onSyncEnd,
    onSyncStart,
    onTrackActivate,
    onWarning,
  });

  if (runtimeRef.current === null || runtimeRef.current.integration.isDestroyed()) {
    runtimeRef.current = createProjectionRuntime(configuration);
    appliedRef.current = { options, rules, scrollRoot: undefined, sourceRoot: undefined };
  }

  const runtime = runtimeRef.current;

  // Deferred to the commit phase: writing directly in the render body would
  // let an interrupted or discarded concurrent render leak its callback
  // props into the ref before React ever commits that render.
  useLayoutEffect(() => {
    callbacksRef.current = {
      onClusterActivate,
      onMarkerActivate,
      onSelectionChange,
      onSyncEnd,
      onSyncStart,
      onTrackActivate,
      onWarning,
    };
  });

  useImperativeHandle(
    ref,
    () => ({
      getState: runtime.integration.getState,
      getStats: runtime.integration.getStats,
      refresh: runtime.integration.render,
      requestRefresh: runtime.integration.requestRender,
      resetStats: runtime.integration.resetStats,
      whenRuntimeDestroyed: runtime.integration.whenDestroyed,
    }),
    [runtime],
  );

  useLayoutEffect(() => {
    lifecycleGenerationRef.current += 1;
    const generation = lifecycleGenerationRef.current;
    const unsubscribes: TrackerEventUnsubscribe[] = [];

    try {
      unsubscribes.push(
        runtime.integration.on('marker:activate', (payload) =>
          notifyConsumer(callbacksRef.current.onMarkerActivate, payload),
        ),
      );
      unsubscribes.push(
        runtime.integration.on('cluster:activate', (payload) =>
          notifyConsumer(callbacksRef.current.onClusterActivate, payload),
        ),
      );
      unsubscribes.push(
        runtime.integration.on('sync:start', (payload) => notifyConsumer(callbacksRef.current.onSyncStart, payload)),
      );
      unsubscribes.push(
        runtime.integration.on('sync:end', (payload) => notifyConsumer(callbacksRef.current.onSyncEnd, payload)),
      );
      unsubscribes.push(
        runtime.integration.on('selection:change', (payload) =>
          notifyConsumer(callbacksRef.current.onSelectionChange, payload),
        ),
      );
      unsubscribes.push(
        runtime.integration.on('track:activate', (payload) =>
          notifyConsumer(callbacksRef.current.onTrackActivate, payload),
        ),
      );
      unsubscribes.push(
        runtime.integration.on('warning', (payload) => notifyConsumer(callbacksRef.current.onWarning, payload)),
      );
    } catch (error) {
      const errors: unknown[] = [error];

      unsubscribes.forEach((unsubscribe) => attemptAdapterCleanup(unsubscribe, errors));
      attemptAdapterCleanup(() => runtime.integration.destroy(), errors);

      throwAdapterLifecycleErrors(errors, 'React Tracker projection setup and rollback both failed.');
    }

    return () => {
      const errors: unknown[] = [];

      attemptAdapterCleanup(() => runtime.integration.unmount(), errors);
      unsubscribes.forEach((unsubscribe) => attemptAdapterCleanup(unsubscribe, errors));

      queueMicrotask(() => {
        if (lifecycleGenerationRef.current === generation) {
          attemptDeferredAdapterCleanup(() => runtime.integration.destroy());
        }
      });

      throwAdapterLifecycleErrors(errors, 'React Tracker projection unmount failed in one or more cleanup steps.');
    };
  }, [runtime]);

  useLayoutEffect(() => {
    const applied = appliedRef.current;
    const rootsChanged =
      applied === null || !Object.is(applied.sourceRoot, sourceRoot) || !Object.is(applied.scrollRoot, scrollRoot);
    const configurationChanged =
      applied === null || !Object.is(applied.options, options) || !Object.is(applied.rules, rules);

    if (rootsChanged && runtime.integration.isMounted()) {
      runtime.integration.unmount();
    }

    if (configurationChanged) {
      runtime.integration.replaceConfiguration(configuration);

      if (runtime.integration.isMounted()) {
        runtime.integration.flushRender();
      }
    }

    if (
      (rootsChanged || !runtime.integration.isMounted()) &&
      sourceRoot !== null &&
      scrollRoot !== null &&
      renderRootRef.current !== null
    ) {
      runtime.integration.mount({
        ...(sourceRoot === undefined ? {} : { sourceRoot }),
        ...(scrollRoot === undefined ? {} : { scrollRoot }),
        renderRoot: renderRootRef.current,
      });
    }

    appliedRef.current = { options, rules, scrollRoot, sourceRoot };
  }, [configuration, options, rules, runtime, scrollRoot, sourceRoot]);

  return <TrackerProjectionTree options={resolvedOptions} renderRootRef={renderRootRef} stores={runtime.stores} />;
}

export type { TrackerHandle, TrackerProps };
export { Tracker };
